SMS.WebApp.Host/Pages/Teacher/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SMS.WebApp.Data.Helper;
using SMS.WebApp.Data.Models.Enums;
using SMS.WebApp.Data.Models.ViewModels;
using SMS.WebApp.Services.IServices;

namespace SMS.WebApp.Host.Pages.Teacher
{
    //[Authorize]
    public class IndexModel : PageModel
    {
        [BindProperty]
        public List<TeacherViewModel> TeacherList { get; set; }
        [BindProperty]
        public TeacherViewModel TeacherVM { get; set; }
        [BindProperty]
        public List<GenderEnum> GenderList { get; set; }
        [BindProperty]
        public DataResult Response { get; set; }

        private readonly ITeacherServicesr _teacherServicesr;
        public IndexModel(ITeacherServicesr teacherServicesr)
        {
            _teacherServicesr = teacherServicesr;
        }

        public async Task<IActionResult> OnGet(DataResult resp)
        {
            var response = await _teacherServicesr.GetAllTeachers();
            TeacherList = response.Data;
            GenderList = Enum.GetValues<GenderEnum>().ToList();
            Response = resp;
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            DataResult response = new DataResult();
            if(TeacherVM.Id.Equals(Guid.Empty))
            {
                response = await _teacherServicesr.CreateTeacher(TeacherVM);
            }
            else
            {
                response = await _teacherServicesr.UpdateTeacher(TeacherVM);
            }
            return RedirectToAction("Index", response);
        }

        public async Task<PartialViewResult> OnGetViewAllPartial()
        {
            //Customers = await _customer.GetAllAsync();
            return new PartialViewResult
            {
                ViewName = "_ViewAll",
                //ViewData = new ViewDataDictionary<IEnumerable<Customer>>(ViewData, Customers)
            };
        }
        public async Task<IActionResult> OnGetDeleteTeacher(Guid id)
        {
            var response = await _teacherServicesr.DeleteTeacher(id);
            return RedirectToAction("Index", response);
        }

        public async Task<IActionResult> OnGetUpdateTeacher(Guid id)
        {
            var response = await _teacherServicesr.GetTeacherByID(id);
            return new OkObjectResult(response.Data.First());
        }
    }
}

SMS.WebApp.Host/Pages/Teacher/Index.cshtml
@page
@model SMS.WebApp.Host.Pages.Teacher.IndexModel
@{
}
<div class="container">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" id="btn">
        <i class="fa-solid fa-plus"></i> Add
    </button>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Gender</th>
                <th scope="col">D.O.B.</th>
                <th scope="col">Subject</th>
                <th scope="col">Phone</th>
                <th scope="col">Email</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.TeacherList.Count > 0)
            {
                @foreach (var item in Model.TeacherList)
                {
                    <tr>
                        <td class="hidden">@item.Id</td>
                        <td>@item.FirstName</td>
                        <td>@item.LastName</td>
                        <td>@item.Gender</td>
                        <td>@item.DOB</td>
                        <td>@item.Subject</td>
                        <td>@item.Phone</td>
                        <td>@item.Email</td>
                        <td>
                            <button id="updateTeacher" onclick="UpdateTeacher('@item.Id')" class="transparentButton">
                                <i class="fa-solid fa-pencil"></i>
                            </button>
                            <a asp-page="/Teacher/Index" asp-route-id="@item.Id" class="deleteButton" asp-page-handler="DeleteTeacher" role="button">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="7" class="text-center">
                        No data.
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="viewAll" class="card-body"></div>
    <!-- Modal -->
    <div class="modal fade" id="teacherCreateUpdate" tabindex="-1" aria-labelledby="teacherCreateUpdate" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-page="/Teacher/Index">
                        <div class="row g-3 form-space">
                            <div class="col">
                                <input type="text" class="form-control hidden" asp-for="@Model.TeacherVM.Id" id="teacherId" />
                                <input type="text" class="form-control" asp-for="@Model.TeacherVM.FirstName" id="firstName" class="firstName form-control" placeholder="First name" aria-label="First name">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" asp-for="@Model.TeacherVM.LastName" id="lastName" placeholder="Last name" aria-label="Last name">
                            </div>
                        </div>
                        <div class="row g-3 form-space">
                            <div class="col">
                                <input type="date" asp-for="@Model.TeacherVM.DOB" id="dob" class="form-control" placeholder="D.O.B." aria-label="DateOfBirth">
                            </div>
                            <div class="col">
                                <select class="form-select" asp-for="@Model.TeacherVM.Gender" id="gender" aria-label="Gender">
                                    <option selected>Select Gender</option>
                                    @{
                                        if (Model.GenderList.Count > 0)
                                        {
                                            foreach (var item in Model.GenderList)
                                            {
                                                <option value="@item">@item</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="row g-3 form-space">
                            <div class="col">
                                <input type="text" asp-for="@Model.TeacherVM.Subject" id="subject" class="subject form-control" placeholder="Subject" aria-label="Subject">
                            </div>
                            <div class="col">
                                <input type="email" class="form-control" id="email" asp-for="@Model.TeacherVM.Email" placeholder="Email" aria-label="Email">
                            </div>
                            <div class="col">
                                <input type="text" class="form-control" id="phone" asp-for="@Model.TeacherVM.Phone" placeholder="Phone" aria-label="Phone">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" id="viewbtn" class="btn btn-secondary" data-bs-dismiss="modal">Demo</button>
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="footer notificationAlert">
    @{
        if(Model.Response.Message != null)
        {
            if(Model.Response.IsSuccess)
            {
                <div class="alert alert-success alert-dismissible fade show">
                    @Model.Response.Message
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }else
            {
                <div class="alert alert-danger alert-dismissible fade show">
                    @Model.Response.Message
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
        }
    }
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $("#btn").click(function () {
            $('#teacherId').val('');
            $('#firstName').val('');
            $('#lastName').val('');
            $('#dob').val('');
            $('#gender').val('');
            $('#subject').val('');
            $('#email').val('');
            $('#phone').val('');
            $("#teacherCreateUpdate").modal('show');
        });

        $("#viewbtn").click(function () {
            $('#viewAll').load('?handler=ViewAllPartial');

        });

        function UpdateTeacher(teacherId)
        {
            //alert(teacherId);
            $.ajax({
                url: "?handler=UpdateTeacher",
                method: "GET",
                data : {id:teacherId},
                success: function (response) {
                    //TODO
                    console.log(response, "response message here")
                    //if(!response.isSuccess)
                    //{
                    //    alert(response.Message)
                    //}
                    //console.log(response.Data, response.Data[0])
                    $('#teacherId').val(response.id);
                    $('#firstName').val(response.firstName);
                    $('#lastName').val(response.lastName);
                    $('#dob').val(response.dob);// TODO man data to date format
                    $('#gender').val(response.gender); // TODO : map data to select list
                    $('#subject').val(response.subject);
                    $('#email').val(response.email);
                    $('#phone').val(response.phone);
                    $("#teacherCreateUpdate").modal('show');
                }
            })
        }

    </script>
}

SMS.WebApp.Host/Pages/Teacher/_ViewAll.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>View ALl here</p>