SMS.WebApp.Host/Pages/Course/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SMS.WebApp.Data.Models.RequestModels;
using SMS.WebApp.Data.Models.ViewModels;
using SMS.WebApp.Services.IServices;

namespace SMS.WebApp.Host.Pages.Course
{
    // Allow Annynomus | Authorize
    [Authorize]
    public class IndexModel : PageModel
    {
        [BindProperty]
        public List<CourseViewModel>? CourseList { get; set; }
        [BindProperty]
        public int PageCount { get; set; }
        private readonly ICourseServices _courseServices;
        private readonly ITeacherServicesr _teacherServices;
        public IndexModel(ICourseServices courseServices, ITeacherServicesr teacherServices)
        {
            _courseServices = courseServices;
            _teacherServices = teacherServices;
        }
        public async Task OnGet(int pageSize, int currentPage)
        {
            //Set Session
            HttpContext.Session.SetString("sessionDemo", "Value Stored in Session");
            RequestQueryParams queryParams = new RequestQueryParams
            {
                PageSize = pageSize == 0 ? 1 : pageSize,
                CurrentPage = currentPage == 0 ? 1 : currentPage
            };
            var response = await _courseServices.GetAllCourse(queryParams);
            if (response.Data != null)
            {
                CourseList = response.Data;
                PageCount = Convert.ToInt32(Math.Ceiling(response.TotalCount / (double)queryParams.PageSize));
            }
        }

        public async Task<PartialViewResult> OnGetCreateCourse()
        {
            //Get Session 
            var sess = HttpContext.Session.GetString("sessionDemo");
            var teacherList = await _teacherServices.GetAllTeachers();
            CourseViewModel courseModel = new CourseViewModel
            {
                Teachers = teacherList.Data,
                SessionExample = sess
            };
            return new PartialViewResult
            {
                ViewName = "_CreateCourse",
                ViewData = new ViewDataDictionary<CourseViewModel>(ViewData, courseModel)
            };
        }

        public async Task<PartialViewResult> OnGetUpdateCourse(Guid id)
        {
            var teacherList = await _teacherServices.GetAllTeachers();
            var course = await _courseServices.GetCourseById(id);
            var courseModel = course.Data.First();
            courseModel.Teachers = teacherList.Data;
            return new PartialViewResult
            {
                ViewName = "_UpdateCourse",
                ViewData = new ViewDataDictionary<CourseViewModel>(ViewData, courseModel)
            };
        }

        public async Task<IActionResult> OnPostAddCourse(CourseViewModel courseArgs)
        {
            var response = await _courseServices.CreateCourse(courseArgs);
            if (response.IsSuccess)
            {
                return RedirectToAction("/Course/Index");
            }
            return Page();
        }

        public async Task<IActionResult> OnGetDeleteCourse(Guid courseId)
        {
            var response = await _courseServices.DeleteCourse(courseId);
            if(response.IsSuccess)
            {
                return RedirectToAction("/Course/Index");
            }
            return Page();
        }
    }
}

SMS.WebApp.Host/Pages/Course/Index.cshtml
@page
@model SMS.WebApp.Host.Pages.Course.IndexModel
@{
}
<div class="container">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" id="addbtn" data-bs-target="#createModal">
        <i class="fa-solid fa-plus"></i> Add
    </button>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Course Name</th>
                <th scope="col">Teacher Name</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.CourseList != null)
            {
                @foreach (var item in Model.CourseList)
                {
                    <tr>
                        <td class="hidden">@item.Id</td>
                        <td>@item.CourseName</td>
                        <td>@item.TeacherFullName</td>
                        <td>
@*                            <button id="updateCourse" onclick="UpdateCourse('@item.Id')" class="transparentButton">
                                <i class="fa-solid fa-pencil"></i>
                            </button>*@
                            <button class="transparentButton" data-bs-toggle="modal" onclick="UpdateCourse('@item.Id')" id="updatebtn" data-bs-target="#updateModal">
                                <i class="fa-solid fa-pencil"></i>
                            </button>
                            <a asp-page="/Course/Index" asp-route-id="@item.Id" class="deleteButton" asp-page-handler="DeleteCourse" role="button">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="7" class="text-center">
                        No data.
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @*Create Modal*@
    <div class="modal fade" tabindex="-1" aria-labelledby="teacherCreateUpdate" id="createModal" aria-hidden="true">
        <div class="modal-dialog">
        </div>
    </div>
    @*Update Modal*@
    <div class="modal fade" tabindex="-1" aria-labelledby="teacherCreateUpdate" id="updateModal" aria-hidden="true">
        <div class="modal-dialog">
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination">'
                    @{
                        if(Model.CourseList != null)
                        {
                            for (int i = 1; i <= Model.PageCount; i++)
                            {
                                <li class="page-item"><a class="page-link" href="@Url.Action("/Course/Index", new { pageSize = 1, currentPage = @i})">@i</a></li>
                            }
                        }
                    }
                    @*<li class="page-item">
                        <a class="page-link" href="@Url.Action("/Course/Index", new { pageSize = 1, currentPage = 1})" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>*@
                </ul>
            </nav>
        </div>
    </footer>
</div>

@section scripts {
    <script type="text/javascript">
        $('#addbtn').click(function() {
            $('#createModal').load('?handler=CreateCourse')
        })
        function UpdateCourse(courseId) {
            $('#updateModal').load('?handler=UpdateCourse&id=' + courseId)
        }
    </script>
}

SMS.WebApp.Host/Pages/Course/_CreateCourse.cshtml
@model CourseViewModel
@{
    
} 
<div class="modal-content modalContainer">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Course</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        @if(Model.SessionExample != null)
        {
            <input type="text" class="form-control" asp-for="@Model.SessionExample" id="teacherId" />
        }
        <form method="post" asp-page="/Course/Index" asp-page-handler="AddCourse">
            <div class="row g-3 form-space">
                <div class="col">
                    <input type="text" class="form-control hidden" asp-for="@Model.Id" id="teacherId" />
                    <input type="text" class="form-control" asp-for="@Model.CourseName" id="courseName" class="courseName form-control" placeholder="Course Name">
                </div>
                <div class="col">
                    <select class="form-select" asp-for="@Model.TeacherId" id="teacher" aria-label="Teacher">
                        <option selected>Select Teacher</option>
                        @{
                            if (Model.Teachers.Count() > 0)
                            {
                                foreach (var item in Model.Teachers)
                                {
                                    <option value="@item.Id">@item.FirstName @item.LastName</option>
                                }
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

SMS.WebApp.Host/Pages/Course/_UpdateCourse.cshtml
@model CourseViewModel
@{
}
<div class="modal-content modalContainer">
    <div class="modal-header">
        <h5 class="modal-title" id="updateModal">Update Course</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <form method="post" asp-page="/Course/Index" asp-page-handler="EditCourse">
            <div class="row g-3 form-space">
                <div class="col">
                    <input type="text" class="form-control hidden" asp-for="@Model.Id" id="teacherId" />
                    <input type="text" class="form-control" asp-for="@Model.CourseName" id="courseName" class="courseName form-control" placeholder="Course Name">
                </div>
                <div class="col">
                    <select class="form-select" asp-for="@Model.TeacherId" id="teacher" aria-label="Teacher">
                        <option selected>Select Teacher</option>
                        @{
                            if (Model.Teachers.Count() > 0)
                            {
                                foreach (var item in Model.Teachers)
                                {
                                    <option value="@item.Id">@item.FirstName @item.LastName</option>
                                }
                            }
                        }
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>